// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace _01.StudentSystem.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddLicense : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddLicense));
        
        string IMigrationMetadata.Id
        {
            get { return "201703101338052_AddLicense"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
